# =========================
# STARSHIP CONFIG
# =========================

format = """$localip$username$directory$git_branch$git_state$python$rust$nodejs$docker_context$dart$aws$conda$memory_usage$nix_shell$package$php$ruby$scala$java$julia$shlvl$swift$cmd_duration$character"""

[localip]
ssh_only = false
format = 'ğŸ“Ÿ [$localipv4](bold red) '
disabled = false

[username]
style_user = "green bold"
style_root = "red bold"
format = "ğŸ‘¤ [$user]($style) "
disabled = false
show_always = true

[hostname]
ssh_only = false
format = 'ğŸ  [$hostname](bold yellow) '
trim_at = "."
disabled = false

[directory]
read_only = " ğŸ”’"
truncation_length = 10
truncate_to_repo = true
style = "bold italic blue"

[git_branch]
symbol = "ğŸŒ¿ "
format = "[$symbol$branch]($style) "
style = "bold green"

[git_state]
format = "[$state]($style) "
style = "bold red"

[python]
symbol = "ğŸ "
format = 'via [${symbol} v${version} (\($virtualenv\))]($style) '
style = "bold yellow"
pyenv_prefix = "venv "
python_binary = ["./venv/bin/python", "python", "python3", "python2"]
detect_extensions = ["py"]
version_format = "v${raw}"

[rust]
symbol = "ğŸ¦€ "
format = "[$symbol]($style) "
style = "bold red"

[nodejs]
symbol = "ğŸŸ¢ "
format = "via [$symbol Node.js $version]($style) "
style = "bold green"
detect_files = ["package.json", ".node-version"]
detect_folders = ["node_modules"]

[docker_context]
symbol = "ğŸ³ "
format = "via [$symbol$context]($style) "
style = "blue bold"
only_with_files = true
detect_files = ["docker-compose.yml", "docker-compose.yaml", "Dockerfile"]
disabled = false

[dart]
symbol = "ğŸ¯ "

[aws]
symbol = "â˜ï¸  "

[conda]
symbol = "ğŸ "

[memory_usage]
symbol = "ğŸ§  "

[nix_shell]
symbol = "âš™ï¸ "

[package]
symbol = "ğŸ“¦ "

[php]
symbol = "ğŸ˜ "

[ruby]
symbol = "ğŸ’ "

[scala]
symbol = "ğŸ”· "

[java]
symbol = "â˜• "

[julia]
symbol = "ğŸŸ£ "

[shlvl]
symbol = "âš¡ "

[swift]
symbol = "ğŸ•Šï¸ "

[character]
success_symbol = "ğŸ’€"
error_symbol = "âœ—"
vicmd_symbol = "âš¡"

[cmd_duration]
min_time = 4
show_milliseconds = false
disabled = false
style = "bold italic red"
